# Generated by Django 3.2.6 on 2022-02-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('extras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOperator',
            fields=[
                ('delivery_operator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.FloatField(default=0)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('role', models.CharField(default='DeliveryOperator', max_length=20)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('online', models.BooleanField(default=True)),
                ('delivering', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('Deliveries', models.ManyToManyField(blank=True, to='orders.Delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.FloatField(default=0)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('role', models.CharField(choices=[('NormalCustomer', 'NormalCustomer'), ('RestaurantCustomer', 'RestaurantCustomer'), ('SuperMarketCustomer', 'SuperMarketCustomer'), ('AgentCustomer', 'AgentCustomer'), ('CompanyCustomer', 'CompanyCustomer')], default='NormalCustomer', max_length=40)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('online', models.BooleanField(default=True)),
                ('addresses', models.ManyToManyField(blank=True, related_name='customer_addresses', related_query_name='customer_addresses', to='extras.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodesForPassReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('role', models.CharField(default='Admin', max_length=20)),
                ('online', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
