# Generated by Django 3.2.6 on 2022-02-08 12:40

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name_ar', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_subtitle', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_subtitle_ar', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_location_ar', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, default='test@gmail.com', max_length=255, null=True)),
                ('company_phone_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_facebook_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_instagram_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, default='', null=True)),
                ('company_description_ar', models.TextField(blank=True, default='', null=True)),
                ('company_features', models.TextField(blank=True, default='', null=True)),
                ('company_features_ar', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='', max_length=255)),
                ('street', models.CharField(default='', max_length=255)),
                ('building_no', models.CharField(default='', max_length=255)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_subtitle_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_description', models.TextField(blank=True, max_length=255, null=True)),
                ('agency_description_ar', models.TextField(blank=True, max_length=255, null=True)),
                ('agency_image', models.FileField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.FileField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='MainValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_provider', models.CharField(choices=[('Visa', 'Visa'), ('Master Card', 'Master Card'), ('Zein Cash', 'Zein Cash')], default='Visa', max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('card_cvc', models.PositiveIntegerField(default=123)),
                ('card_expire_date', models.DateField(default='1999-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_content', models.TextField()),
                ('rating_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_services', models.TextField(blank=True, default='', null=True)),
                ('our_services_ar', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
