# Generated by Django 3.2.6 on 2022-02-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_roles', '0001_initial'),
        ('extras', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.customer'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='meals',
            field=models.ManyToManyField(blank=True, to='products.Meal'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.customer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='meal_rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.meal'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='user_roles.customer'),
        ),
        migrations.AddField(
            model_name='about',
            name='carousel_images',
            field=models.ManyToManyField(blank=True, related_name='carousel_images', to='extras.CarouselImage'),
        ),
    ]
