# Generated by Django 3.2.6 on 2022-02-08 12:40

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_report', models.TextField(default='Some Problem Occured')),
                ('delivery_problem_report_choice', models.CharField(blank=True, choices=[('test', 'test'), ('test2', 'test2'), ('test3', 'test3')], max_length=255)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_being_delivered', models.BooleanField(default=False)),
                ('city', models.CharField(default='USA', max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default='0', max_length=63)),
                ('lang', models.CharField(default='0', max_length=255)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('lat', models.CharField(default='0', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('pay_home', models.BooleanField(default=False)),
                ('destination', location_field.models.plain.PlainLocationField(default='0', max_length=63)),
                ('lang', models.CharField(default='0', max_length=255)),
                ('lat', models.CharField(default='0', max_length=255)),
                ('bill', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('order_note', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('package_review', models.FloatField(default=0.0)),
                ('delivery_review', models.FloatField(default=0.0)),
                ('comment', models.TextField(default='', null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
