# Generated by Django 3.2.6 on 2022-02-08 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_name_ar', models.CharField(default='', max_length=255)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('meals_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_name_ar', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_name_ar', models.CharField(default='', max_length=255)),
                ('meal_description', models.TextField()),
                ('meal_description_ar', models.TextField(default='')),
                ('customer_meal_price', models.PositiveIntegerField(default=0)),
                ('supermarket_meal_price', models.PositiveIntegerField(default=0)),
                ('agent_meal_price', models.PositiveIntegerField(default=0)),
                ('restaurant_meal_price', models.PositiveIntegerField(default=0)),
                ('company_meal_price', models.PositiveIntegerField(default=0)),
                ('meal_points', models.FloatField(default=0.0)),
                ('meal_rating', models.FloatField(default=0)),
                ('meal_order_times', models.PositiveIntegerField(default=0)),
                ('meal_main_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('meal_delivery_time', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category')),
                ('meal_ingredients', models.ManyToManyField(blank=True, related_name='meal_ingredients', to='products.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=255)),
                ('offer_name_ar', models.CharField(default='', max_length=255)),
                ('normal_customer_offer_price', models.PositiveIntegerField(default=0)),
                ('supermarket_customer_offer_price', models.PositiveIntegerField(default=0)),
                ('agent_customer_offer_price', models.PositiveIntegerField(default=0)),
                ('company_customer_offer_price', models.PositiveIntegerField(default=0)),
                ('restuarant_customer_offer_price', models.PositiveIntegerField(default=0)),
                ('normal_customer_offer_description', models.TextField(default='', null=True)),
                ('supermarket_customer_offer_description', models.TextField(default='', null=True)),
                ('agent_customer_offer_description', models.TextField(default='', null=True)),
                ('company_customer_offer_description', models.TextField(default='', null=True)),
                ('restuarant_customer_offer_description', models.TextField(default='', null=True)),
                ('normal_customer_offer_description_ar', models.TextField(default='', null=True)),
                ('supermarket_customer_offer_description_ar', models.TextField(default='', null=True)),
                ('agent_customer_offer_description_ar', models.TextField(default='', null=True)),
                ('company_customer_offer_description_ar', models.TextField(default='', null=True)),
                ('restuarant_customer_offer_description_ar', models.TextField(default='', null=True)),
                ('offer_image', models.FileField(null=True, upload_to='static/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.meal')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('image', models.FileField(upload_to='static/images/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_offers',
            field=models.ManyToManyField(blank=True, related_name='meal_offers', to='products.Offer'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_owner', to='user_roles.customer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_items', models.ManyToManyField(blank=True, to='products.CartItem')),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to='user_roles.customer')),
            ],
        ),
    ]
